name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Terraform
      run: sudo apt-get install -y unzip
      run: wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      run: unzip terraform_0.15.5_linux_amd64.zip
      run: sudo mv terraform /usr/local/bin/

    - name: Init and Plan
      run: terraform init -backend-config="bucket=my-terraform-state-bucket" -backend-config="key=path/to/my/state/file" -backend-config="region=us-east-1"
      run: terraform plan

    - name: Apply
      run: terraform apply -auto-approve
